development:
  sessions:
    default:
      database: bonnie_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: bonnie_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: bonnie
      hosts:
        - <%= ENV.fetch('BONNIE_DB_HOSTNAME', 'localhost') %>:<%= ENV.fetch('BONNIE_DB_PORT', '27017') %>
      username: <%= ENV.fetch('BONNIE_DB_USER', 'BONNIE') %>
      password: <%= ENV.fetch('BONNIE_DB_PASSWORD', 'password') %>
